from qiskit import QuantumCircuit, QuantumRegister


def build_adder_circuit(n: int):
    """
    Return the adder circuit for n-bit inputs.
    == Input ==
    n : int
        Bit-width of x and y (each stored in n+1 qubits; n ≥ 1).

    == Return ==
    qc        : QuantumCircuit
    x_reg     : QuantumRegister  — untouched by the circuit
    y_reg     : QuantumRegister  — overwritten by x + y
    carry_reg : QuantumRegister  — ancillary qubits, starts and ends at |0⟩
    """
    m = n + 1  # qubits per data register

    x_reg = QuantumRegister(m, "x")
    y_reg = QuantumRegister(m, "y")
    # carry[0] is the carry-in for bit 0, permanently |0⟩.
    # carry[i+1] holds the carry-out of bit position i.
    carry = QuantumRegister(m, "c")

    qc = QuantumCircuit(x_reg, y_reg, carry, name=f"adder(n={n})")

    # The forward sweep computes the carry generated by every bit.
    # In this loop, i goes from 0 to n - 1, hence it operates on
    # all n qubits of the input.
    for i in range(n):
        a    = x_reg[i]
        b    = y_reg[i]
        cin  = carry[i]
        cout = carry[i + 1]

        # here ccx is toffoli gate is ccx, it represents c ^= a ^ b
        # and it does the xor for assignment as we want the gate to
        # reversible.
        # cout ^= a & b
        qc.ccx(a, b, cout)
        # b ^= a
        qc.cx(a, b)
        # cout ^= cin & b
        qc.ccx(cin, b, cout)

    # Compute the overflow bit
    # Since the assignment rules specify that x + y < pow(2, n+1),
    # carry[n] is basically the carry produced by nth bit of x, y.
    # Due to given, we know that x[n] and y[n] are always 0, we can
    # just assign carry[n-1] to y[n].
    qc.cx(carry[n], y_reg[n])

    # We do a backward sweep to uncompute the carry registers and 
    # compute the sum with carry. In this loop, i goes from n - 1
    # to 0, hence it operates on all n qubits of the input but in
    # a reverse order.
    for i in range(n - 1, -1, -1):
        a    = x_reg[i]
        b    = y_reg[i]
        cin  = carry[i]
        cout = carry[i + 1]

        # Here we inverse the carry operation, by going reverse
        # cout ^= a & b
        qc.ccx(cin, b, cout)
        # b ^= a
        qc.cx(a, b)
        # cout ^= cin & b
        qc.ccx(a, b, cout)

        # Sum gate: y[i] = x[i] XOR y[i] XOR cin
        # no-op when cin = |0⟩ (i = 0)
        # b ^= cin
        qc.cx(cin, b)
        # b ^= a
        qc.cx(a, b)

    return qc, x_reg, y_reg, carry


if __name__ == "__main__":
    n = 2
    qc, _, _, _ = build_adder_circuit(n)
    print(qc.draw(output="text", fold=120))